### ISSUE TITLE
Concurrent map iteration and write exception

### ISSUE THREAD

**Issue by watchforstock** [goccy/go-json#307]
I'm using the library in an application where multiple go-routines are marshalling JSON (potentially at the same time). Although I've run a number of times successfully, today I got a concurrent map access exception from within the go-json library. Is the library intended to be thread-safe?

The stack trace given was:
```fatal error: concurrent map iteration and map write
goroutine 3287070 [running]:
runtime.throw({0x1830962, 0x10000000186d480})
        /usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc04931da40 sp=0xc04931da10 pc=0x444e91
runtime.mapiternext(0x1787760)
        /usr/local/go/src/runtime/map.go:858 +0x4eb fp=0xc04931dab0 sp=0xc04931da40 pc=0x41f26b
runtime.mapiterinit(0x1, 0xc04931db00, 0xc0438baa80)
        /usr/local/go/src/runtime/map.go:848 +0x236 fp=0xc04931dad0 sp=0xc04931dab0 pc=0x41ed36
reflect.mapiterinit(0x1a95250, 0xc0438baa80)
        /usr/local/go/src/runtime/map.go:1340 +0x45 fp=0xc04931db10 sp=0xc04931dad0 pc=0x472065
github.com/goccy/go-json/internal/encoder/vm.Run(0xc0777cc000, {0xc0438baa80, 0x0, 0x6a80}, 0xc00013b1c0)
        /home/astock/go/pkg/mod/github.com/goccy/go-json@v0.8.1/internal/encoder/vm/vm.go:406 +0x2ad7 fp=0xc049320fc0 sp=0xc04931db10 pc=0x10a03d7
github.com/goccy/go-json.encodeRunCode(0x203012, {0xc0438baa80, 0x203012, 0xc04a82bb00}, 0xc0c545de80)
        /home/astock/go/pkg/mod/github.com/goccy/go-json@v0.8.1/encode.go:307 +0x68 fp=0xc049320ff8 sp=0xc049320fc0 pc=0x10ca968
github.com/goccy/go-json.encode(0xc0777cc000, {0x1755620, 0xc04a82bb00})
        /home/astock/go/pkg/mod/github.com/goccy/go-json@v0.8.1/encode.go:232 +0x21c fp=0xc049321078 sp=0xc049320ff8 pc=0x10ca85c
github.com/goccy/go-json.marshal({0x1755620, 0xc04a82bb00}, {0x0, 0x0, 0xc0cfc5d128})
        /home/astock/go/pkg/mod/github.com/goccy/go-json@v0.8.1/encode.go:147 +0xba fp=0xc0493210d8 sp=0xc049321078 pc=0x10ca51a
github.com/goccy/go-json.MarshalWithOption(...)
        /home/astock/go/pkg/mod/github.com/goccy/go-json@v0.8.1/json.go:186
github.com/goccy/go-json.Marshal({0x1755620, 0xc04a82bb00})
        /home/astock/go/pkg/mod/github.com/goccy/go-json@v0.8.1/json.go:171 +0x2a fp=0xc049321110 sp=0xc0493210d8 pc=0x10ca9ea```

Thanks

Andrew

**Comment by goccy** [comment]
The current implementation doesn't lock when encoding the map.
Therefore, if you refer and encode the same map from multiple goroutines, panic may occur.

Perhaps this will happen with the standard library as well.

**Comment by watchforstock** [comment]
Thanks for the fast reply. As far as I'm aware I'm not using the data I'm encoding elsewhere while marshalling as each goroutine creates and manages its own data. I will have a check/think about whether there could be concurrent access.

As far as you're aware / expecting, I should be able to concurrently call Marshal on different objects without potential for issues - is that correct?

Thanks

**Comment by watchforstock** [comment]
As an additional comment, I've never seen this error with the standard library so I either got unlucky (possibly) or it's a difference in the implementations (I've only recently switch to go-json to try to improve performance).

**Comment by goccy** [comment]
I agree. If uses different map object in all goroutines,  i think that the map object could be encoded without problems.
If you encounter problems in that state, it's likely that there is a problem with go-json, so I'll investigate it.

**Comment by OlegElizarov** [comment]
I had same problem in 0.8.1 version. Than updated to master(0.8.2) and got 


```
recovered from panic: runtime error: makeslice: len out of range
goroutine 8473 [running]:
runtime/debug.Stack()
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/runtime/debug/stack.go:24 +0x88
gitlab.ozon.ru/platform/scratch/pkg/mw/http.Recover.func1.1(0x14001869200, {0x1065a3200, 0x1402acbbc50})
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/runtime/panic.go:1038 +0x21c
github.com/goccy/go-json/internal/encoder.NewMapContext(0x6e656e6f706d6f63)
	/Users/oelizarov/go/pkg/mod/github.com/goccy/go-json@v0.8.2-0.20211227143828-2d98d47d0f92/internal/encoder/encoder.go:265 +0x88
github.com/goccy/go-json/internal/encoder/vm.Run(0x140006ecd00, {0x14013038000, 0x0, 0x400}, 0x1401243c0c0)
	/Users/oelizarov/go/pkg/mod/github.com/goccy/go-json@v0.8.2-0.20211227143828-2d98d47d0f92/internal/encoder/vm/vm.go:406 +0x2b4c
github.com/goccy/go-json.encodeRunCode(0x140006ecd00, {0x14013038000, 0x0, 0x400}, 0x1401243c0c0)
	/Users/oelizarov/go/pkg/mod/github.com/goccy/go-json@v0.8.2-0.20211227143828-2d98d47d0f92/encode.go:307 +0x170
github.com/goccy/go-json.encode(0x140006ecd00, {0x10636c3e0, 0x1402f73ef60})
	/Users/oelizarov/go/pkg/mod/github.com/goccy/go-json@v0.8.2-0.20211227143828-2d98d47d0f92/encode.go:232 +0x288
github.com/goccy/go-json.marshal({0x10636c3e0, 0x1402f73ef60}, {0x0, 0x0, 0x0})
	/Users/oelizarov/go/pkg/mod/github.com/goccy/go-json@v0.8.2-0.20211227143828-2d98d47d0f92/encode.go:147 +0xbc
github.com/goccy/go-json.MarshalWithOption(...)
	/Users/oelizarov/go/pkg/mod/github.com/goccy/go-json@v0.8.2-0.20211227143828-2d98d47d0f92/json.go:186
github.com/goccy/go-json.Marshal({0x10636c3e0, 0x1402f73ef60})
	/Users/oelizarov/go/pkg/mod/github.com/goccy/go-json@v0.8.2-0.20211227143828-2d98d47d0f92/json.go:171 +0x38
	
```
This marshal() is called in child goroutine of http.Serve . My struct is ~ 
map[string]interface{"text1":[]element{element{field1:map[string]interface{}}}} 

Can't repeat problem in single goroutine with that struct, but if field1 is nil or empty(len=0) than it doesn't panic
There is no panic if using encoding/json , json-iterator or sonic

Hope that you will fix it , because I like this project. ❤️

**Comment by goccy** [comment]
Thank you for the reporting. 
I tried to reproduce this problem, but still I couldn't ...
My testing codes is the following .

```go
package json_test

import (
	"sync"
	"testing"

	"github.com/goccy/go-json"
)

func TestEncodeConcurrentMap(t *testing.T) {
	type T struct {
		M map[string]interface{}
	}
	n := 100000
	var wg sync.WaitGroup
	wg.Add(n)
	for i := 0; i < n; i++ {
		go func() {
			v := map[string]interface{}{
				"a": []T{
					{
						M: map[string]interface{}{
							"foo": "bar",
						},
					},
				},
				"b": "baz",
			}
			for j := 0; j < 10; j++ {
				if _, err := json.Marshal(v); err != nil {
					t.Fatal(err)
				}
			}
			wg.Done()
		}()
	}
	wg.Wait()
}
```

**Comment by watchforstock** [comment]
Thanks for following this up. After raising this, we got another (but different) concurrent access error while JSON marshalling. I now suspect that there was some object sharing between the goroutines and that may have been the cause of this error. We've put a fix into our codebase and will try this library again and see if we see the issue again.

**Comment by Max-Cheng** [comment]
> Thanks for following this up. After raising this, we got another (but different) concurrent access error while JSON marshalling. I now suspect that there was some object sharing between the goroutines and that may have been the cause of this error. We've put a fix into our codebase and will try this library again and see if we see the issue again.

I got the same problem with copy a `sync.Map` to a normal build-in normal map

**Comment by goccy** [comment]
@Max-Cheng 
Wow! Is it possible to write reproducible test code?

**Comment by Max-Cheng** [comment]
Context:
```go

rawdata:=&sync.Map{}
// Add some data
targetMap:=make(map[string]interface{})


rawdata.Range(func(key,value interface{})bool{
    targetMap[key.(string)] = value
})


data:=gjson.Marshal(targetmap)              // panic here
```

Stack:

```
goroutine 43 [running]:
runtime.throw({0x10536923a, 0x26})
	/Users/co1a/go/go1.17.5/src/runtime/panic.go:1198 +0x54 fp=0x1400130f210 sp=0x1400130f1e0 pc=0x104c58804
runtime.mapiternext(0x140001402c0)
	/Users/co1a/go/go1.17.5/src/runtime/map.go:858 +0x538 fp=0x1400130f290 sp=0x1400130f210 pc=0x104c30708
reflect.mapiternext(0x140001402c0)
	/Users/co1a/go/go1.17.5/src/runtime/map.go:1346 +0x28 fp=0x1400130f2b0 sp=0x1400130f290 pc=0x104c884a8
github.com/goccy/go-json/internal/encoder/vm.Run(0x140012c4000, {0x14000f22000, 0x0, 0x400}, 0x140006441c0)
	/Users/co1a/go/pkg/mod/github.com/goccy/go-json@v0.9.1/internal/encoder/vm/vm.go:457 +0x6e0 fp=0x14001313b90 sp=0x1400130f2b0 pc=0x104fd2370
github.com/goccy/go-json.encodeRunCode(0x140012c4000, {0x14000f22000, 0x0, 0x400}, 0x140006441c0)
	/Users/co1a/go/pkg/mod/github.com/goccy/go-json@v0.9.1/encode.go:308 +0x170 fp=0x14001313bf0 sp=0x14001313b90 pc=0x104ffee20
github.com/goccy/go-json.encodeNoEscape(0x140012c4000, {0x105505180, 0x14001313e40})
	/Users/co1a/go/pkg/mod/github.com/goccy/go-json@v0.9.1/encode.go:259 +0x1d0 fp=0x14001313c80 sp=0x14001313bf0 pc=0x104ffebf0
github.com/goccy/go-json.marshalNoEscape({0x105505180, 0x1400006de40})
	/Users/co1a/go/pkg/mod/github.com/goccy/go-json@v0.9.1/encode.go:172 +0x7c fp=0x14001313d00 sp=0x14001313c80 pc=0x104ffe59c
github.com/goccy/go-json.MarshalNoEscape(...)
	/Users/co1a/go/pkg/mod/github.com/goccy/go-json@v0.9.1/json.go:176
```


I'll try to help you add some unit test code.

**Comment by Max-Cheng** [comment]
> Context:
> 
> ```go
> rawdata:=&sync.Map{}
> // Add some data
> targetMap:=make(map[string]interface{})
> 
> 
> rawdata.Range(func(key,value interface{})bool{
>     targetMap[key.(string)] = value
> })
> 
> 
> data:=gjson.Marshal(targetmap)              // panic here
> ```
> 
> Stack:
> 
> ```
> goroutine 43 [running]:
> runtime.throw({0x10536923a, 0x26})
> 	/Users/co1a/go/go1.17.5/src/runtime/panic.go:1198 +0x54 fp=0x1400130f210 sp=0x1400130f1e0 pc=0x104c58804
> runtime.mapiternext(0x140001402c0)
> 	/Users/co1a/go/go1.17.5/src/runtime/map.go:858 +0x538 fp=0x1400130f290 sp=0x1400130f210 pc=0x104c30708
> reflect.mapiternext(0x140001402c0)
> 	/Users/co1a/go/go1.17.5/src/runtime/map.go:1346 +0x28 fp=0x1400130f2b0 sp=0x1400130f290 pc=0x104c884a8
> github.com/goccy/go-json/internal/encoder/vm.Run(0x140012c4000, {0x14000f22000, 0x0, 0x400}, 0x140006441c0)
> 	/Users/co1a/go/pkg/mod/github.com/goccy/go-json@v0.9.1/internal/encoder/vm/vm.go:457 +0x6e0 fp=0x14001313b90 sp=0x1400130f2b0 pc=0x104fd2370
> github.com/goccy/go-json.encodeRunCode(0x140012c4000, {0x14000f22000, 0x0, 0x400}, 0x140006441c0)
> 	/Users/co1a/go/pkg/mod/github.com/goccy/go-json@v0.9.1/encode.go:308 +0x170 fp=0x14001313bf0 sp=0x14001313b90 pc=0x104ffee20
> github.com/goccy/go-json.encodeNoEscape(0x140012c4000, {0x105505180, 0x14001313e40})
> 	/Users/co1a/go/pkg/mod/github.com/goccy/go-json@v0.9.1/encode.go:259 +0x1d0 fp=0x14001313c80 sp=0x14001313bf0 pc=0x104ffebf0
> github.com/goccy/go-json.marshalNoEscape({0x105505180, 0x1400006de40})
> 	/Users/co1a/go/pkg/mod/github.com/goccy/go-json@v0.9.1/encode.go:172 +0x7c fp=0x14001313d00 sp=0x14001313c80 pc=0x104ffe59c
> github.com/goccy/go-json.MarshalNoEscape(...)
> 	/Users/co1a/go/pkg/mod/github.com/goccy/go-json@v0.9.1/json.go:176
> ```
> 
> I'll try to help you add some unit test code.

Not only `v0.9.1``v0.9.4`

**Comment by goccy** [comment]
Ah, Looking at the stack trace, it seems that you are using `json.MarshalNoEscape` instead of `json.Marshal` . This does not escape the argument, so this API will cause problems depending on the timing of the GC. I want to know the pattern of bugs that occur in json.Marshal.

**Comment by Max-Cheng** [comment]
> Ah, Looking at the stack trace, it seems that you are using `json.MarshalNoEscape` instead of `json.Marshal` . This does not escape the argument, so this API will cause problems depending on the timing of the GC. I want to know the pattern of bugs that occur in json.Marshal.

Nope. I using default pattern

**Comment by goccy** [comment]
@Max-Cheng Ummm... `json.MarshalNoEscape` is always used in the stack traces you posted.

**Comment by Max-Cheng** [comment]
No more panic after using `map[string]interface{}` and `gjson.marshal`, thanks! @goccy

**Comment by goccy** [comment]
@Max-Cheng Thank you for your report !!

@watchforstock @OlegElizarov 
This problem may have been fixed by some modifications to the map encoder.
If you encounter similar issues with v0.9.6 or later, please reopen this.

**Comment by itziklavon** [comment]
@goccy 
i'm still having this issue on v0.9.10
i don;t know how to reproduce it, but it happens once in a couple of days on my server
golang version 1.18

stack trace:
```
fatal error: concurrent map iteration and map write
--
Sat, Aug 27 2022 3:47:12 pm |  
Sat, Aug 27 2022 3:47:12 pm | goroutine 70 [running]:
Sat, Aug 27 2022 3:47:12 pm | runtime.throw({0x16d3ae8?, 0x1?})
Sat, Aug 27 2022 3:47:12 pm | /usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc000f0c258 sp=0xc000f0c228 pc=0x43a1f1
Sat, Aug 27 2022 3:47:12 pm | runtime.mapiternext(0xe?)
Sat, Aug 27 2022 3:47:12 pm | /usr/local/go/src/runtime/map.go:871 +0x4eb fp=0xc000f0c2c8 sp=0xc000f0c258 pc=0x411bcb
Sat, Aug 27 2022 3:47:12 pm | reflect.mapiternext(0x3?)
Sat, Aug 27 2022 3:47:12 pm | /usr/local/go/src/runtime/map.go:1378 +0x19 fp=0xc000f0c2e0 sp=0xc000f0c2c8 pc=0x4665d9
Sat, Aug 27 2022 3:47:12 pm | github.com/goccy/go-json/internal/encoder/vm.Run(0xc002a0cf70, {0xc00107a000?, 0x527ddc?, 0x0?}, 0x8?)
Sat, Aug 27 2022 3:47:12 pm | /go/pkg/mod/github.com/goccy/go-json@v0.9.10/internal/encoder/vm/vm.go:461 +0x75b fp=0xc000f0f720 sp=0xc000f0c2e0 pc=0xa026db
Sat, Aug 27 2022 3:47:12 pm | github.com/goccy/go-json.encodeRunCode(0xc000f0f790?, {0xc00107a000?, 0xc003a214a0?, 0x1?}, 0xc000f0f7a8?)
Sat, Aug 27 2022 3:47:12 pm | /go/pkg/mod/github.com/goccy/go-json@v0.9.10/encode.go:310 +0x68 fp=0xc000f0f758 sp=0xc000f0f720 pc=0xa2eb28
Sat, Aug 27 2022 3:47:12 pm | github.com/goccy/go-json.encode(0xc002a0cf70, {0x140be80, 0xc00542cdd0})
Sat, Aug 27 2022 3:47:12 pm | /go/pkg/mod/github.com/goccy/go-json@v0.9.10/encode.go:235 +0x21c fp=0xc000f0f7d8 sp=0xc000f0f758 pc=0xa2ea1c
Sat, Aug 27 2022 3:47:12 pm | github.com/goccy/go-json.marshal({0x140be80, 0xc00542cdd0}, {0x0, 0x0, 0x40cf76?})
Sat, Aug 27 2022 3:47:12 pm | /go/pkg/mod/github.com/goccy/go-json@v0.9.10/encode.go:150 +0xba fp=0xc000f0f838 sp=0xc000f0f7d8 pc=0xa2e6da
Sat, Aug 27 2022 3:47:12 pm | github.com/goccy/go-json.MarshalWithOption(...)
Sat, Aug 27 2022 3:47:12 pm | /go/pkg/mod/github.com/goccy/go-json@v0.9.10/json.go:186
Sat, Aug 27 2022 3:47:12 pm | github.com/goccy/go-json.Marshal({0x140be80?, 0xc00542cdd0?})
Sat, Aug 27 2022 3:47:12 pm |  /go/pkg/mod/github.com/goccy/go-json@v0.9.10/json.go:171 +0x2a fp=0xc000f0f870 sp=0xc000f0f838 pc=0xa2ebaa
--
Sat, Aug 27 2022 3:47:12 pm | bonus-management-go/services/bonuses/bonus_limits.createBonusLog({_, _, _}, _, _, {0x5c077d2, {{0xc006417320, 0x0}, {0xc0064172a0, 0x0}, ...}, ...})
